"""Stat display constants and formatting, ported from display_constants.js."""

from __future__ import annotations

from typing import Any

ID_PREFIXES: dict[str, str] = {
    "displayName": "",
    "lvl": "Combat Level Min: ",
    "classReq": "Class Req: ",
    "strReq": "Strength Min: ",
    "dexReq": "Dexterity Min: ",
    "intReq": "Intelligence Min: ",
    "defReq": "Defense Min: ",
    "agiReq": "Agility Min: ",
    "nDam_": "Neutral Damage: ",
    "eDam_": "Earth Damage: ",
    "tDam_": "Thunder Damage: ",
    "wDam_": "Water Damage: ",
    "fDam_": "Fire Damage: ",
    "aDam_": "Air Damage: ",
    "atkSpd": "Attack Speed: ",
    "hp": "Health : ",
    "eDef": "Earth Defense: ",
    "tDef": "Thunder Defense: ",
    "wDef": "Water Defense: ",
    "fDef": "Fire Defense: ",
    "aDef": "Air Defense: ",
    "str": "Strength: ",
    "dex": "Dexterity: ",
    "int": "Intelligence: ",
    "def": "Defense: ",
    "agi": "Agility: ",
    "hpBonus": "Health Bonus: ",
    "hprRaw": "Raw Health Regen: ",
    "hprPct": "Health Regen %: ",
    "healPct": "Heal Effectiveness %: ",
    "sdRaw": "Spell Damage Raw: ",
    "rSdRaw": "Elem. Spell Damage Raw: ",
    "nSdRaw": "Neut. Spell Damage Raw: ",
    "eSdRaw": "Earth Spell Damage Raw: ",
    "tSdRaw": "Thunder Spell Damage Raw: ",
    "wSdRaw": "Water Spell Damage Raw: ",
    "fSdRaw": "Fire Spell Damage Raw: ",
    "aSdRaw": "Air Spell Damage Raw: ",
    "sdPct": "Spell Damage %: ",
    "rSdPct": "Elem. Spell Damage %: ",
    "nSdPct": "Neut. Spell Damage %: ",
    "eSdPct": "Earth Spell Damage %: ",
    "tSdPct": "Thunder Spell Damage %: ",
    "wSdPct": "Water Spell Damage %: ",
    "fSdPct": "Fire Spell Damage %: ",
    "aSdPct": "Air Spell Damage %: ",
    "mdRaw": "Melee Damage Raw: ",
    "rMdRaw": "Elem. Melee Damage Raw: ",
    "nMdRaw": "Neut. Melee Damage Raw: ",
    "eMdRaw": "Earth Melee Damage Raw: ",
    "tMdRaw": "Thunder Melee Damage Raw: ",
    "wMdRaw": "Water Melee Damage Raw: ",
    "fMdRaw": "Fire Melee Damage Raw: ",
    "aMdRaw": "Air Melee Damage Raw: ",
    "mdPct": "Melee Damage %: ",
    "rMdPct": "Elem. Melee Damage %: ",
    "nMdPct": "Neut. Melee Damage %: ",
    "eMdPct": "Earth Melee Damage %: ",
    "tMdPct": "Thunder Melee Damage %: ",
    "wMdPct": "Water Melee Damage %: ",
    "fMdPct": "Fire Melee Damage %: ",
    "aMdPct": "Air Melee Damage %: ",
    "damRaw": "Damage Raw: ",
    "rDamRaw": "Elemental Damage Raw: ",
    "nDamRaw": "Neutral Damage Raw: ",
    "eDamRaw": "Earth Damage Raw: ",
    "tDamRaw": "Thunder Damage Raw: ",
    "wDamRaw": "Water Damage Raw: ",
    "fDamRaw": "Fire Damage Raw: ",
    "aDamRaw": "Air Damage Raw: ",
    "damPct": "Damage %: ",
    "rDamPct": "Elemental Damage %: ",
    "nDamPct": "Neutral Damage %: ",
    "eDamPct": "Earth Damage %: ",
    "tDamPct": "Thunder Damage %: ",
    "wDamPct": "Water Damage %: ",
    "fDamPct": "Fire Damage %: ",
    "aDamPct": "Air Damage %: ",
    "critDamPct": "Crit Damage Bonus %: ",
    "mr": "Mana Regen: ",
    "ms": "Mana Steal: ",
    "ref": "Reflection: ",
    "ls": "Life Steal: ",
    "poison": "Poison: ",
    "thorns": "Thorns: ",
    "expd": "Exploding: ",
    "spd": "Walk Speed Bonus: ",
    "atkTier": "Attack Speed Bonus: ",
    "eDefPct": "Earth Defense %: ",
    "tDefPct": "Thunder Defense %: ",
    "wDefPct": "Water Defense %: ",
    "fDefPct": "Fire Defense %: ",
    "aDefPct": "Air Defense %: ",
    "rDefPct": "Elemental Defense %: ",
    "spPct1": "1st Spell Cost %: ",
    "spRaw1": "1st Spell Cost Raw: ",
    "spPct2": "2nd Spell Cost %: ",
    "spRaw2": "2nd Spell Cost Raw: ",
    "spPct3": "3rd Spell Cost %: ",
    "spRaw3": "3rd Spell Cost Raw: ",
    "spPct4": "4th Spell Cost %: ",
    "spRaw4": "4th Spell Cost Raw: ",
    "sprint": "Sprint Bonus: ",
    "sprintReg": "Sprint Regen Bonus: ",
    "jh": "Jump Height: ",
    "xpb": "Combat XP Bonus: ",
    "lb": "Loot Bonus: ",
    "lq": "Loot Quality: ",
    "spRegen": "Soul Point Regen: ",
    "eSteal": "Stealing: ",
    "gXp": "Gathering XP Bonus: ",
    "gSpd": "Gathering Speed Bonus: ",
    "kb": "Knockback: ",
    "weakenEnemy": "Weaken Enemy: ",
    "slowEnemy": "Slow Enemy: ",
    "maxMana": "Max Mana: ",
    "mainAttackRange": "Melee Range %: ",
    "slots": "Powder Slots: ",
    "set": "Set: ",
    "quest": "Quest Req: ",
    "restrict": "",
    "lore": "",
}

ID_SUFFIXES: dict[str, str] = {
    "displayName": "",
    "lvl": "",
    "classReq": "",
    "strReq": "",
    "dexReq": "",
    "intReq": "",
    "defReq": "",
    "agiReq": "",
    "nDam_": "",
    "eDam_": "",
    "tDam_": "",
    "wDam_": "",
    "fDam_": "",
    "aDam_": "",
    "atkSpd": "",
    "hp": "",
    "eDef": "",
    "tDef": "",
    "wDef": "",
    "fDef": "",
    "aDef": "",
    "str": "",
    "dex": "",
    "int": "",
    "def": "",
    "agi": "",
    "hpBonus": "",
    "hprRaw": "",
    "hprPct": "%",
    "healPct": "%",
    "sdRaw": "",
    "rSdRaw": "",
    "nSdRaw": "",
    "eSdRaw": "",
    "tSdRaw": "",
    "wSdRaw": "",
    "fSdRaw": "",
    "aSdRaw": "",
    "sdPct": "%",
    "rSdPct": "%",
    "nSdPct": "%",
    "eSdPct": "%",
    "tSdPct": "%",
    "wSdPct": "%",
    "fSdPct": "%",
    "aSdPct": "%",
    "mdRaw": "",
    "rMdRaw": "",
    "nMdRaw": "",
    "eMdRaw": "",
    "tMdRaw": "",
    "wMdRaw": "",
    "fMdRaw": "",
    "aMdRaw": "",
    "mdPct": "%",
    "rMdPct": "%",
    "nMdPct": "%",
    "eMdPct": "%",
    "tMdPct": "%",
    "wMdPct": "%",
    "fMdPct": "%",
    "aMdPct": "%",
    "damRaw": "",
    "rDamRaw": "",
    "nDamRaw": "",
    "eDamRaw": "",
    "tDamRaw": "",
    "wDamRaw": "",
    "fDamRaw": "",
    "aDamRaw": "",
    "damPct": "%",
    "rDamPct": "%",
    "nDamPct": "%",
    "eDamPct": "%",
    "tDamPct": "%",
    "wDamPct": "%",
    "fDamPct": "%",
    "aDamPct": "%",
    "critDamPct": "%",
    "mr": "/5s",
    "ms": "/3s",
    "ref": "%",
    "ls": "/3s",
    "poison": "/3s",
    "thorns": "%",
    "expd": "%",
    "spd": "%",
    "atkTier": " tier",
    "eDefPct": "%",
    "tDefPct": "%",
    "wDefPct": "%",
    "fDefPct": "%",
    "aDefPct": "%",
    "rDefPct": "%",
    "spPct1": "%",
    "spRaw1": "",
    "spPct2": "%",
    "spRaw2": "",
    "spPct3": "%",
    "spRaw3": "",
    "spPct4": "%",
    "spRaw4": "",
    "sprint": "%",
    "sprintReg": "%",
    "jh": "",
    "xpb": "%",
    "lb": "%",
    "lq": "%",
    "spRegen": "%",
    "eSteal": "%",
    "gXp": "%",
    "gSpd": "%",
    "kb": "%",
    "weakenEnemy": "%",
    "slowEnemy": "%",
    "maxMana": "",
    "mainAttackRange": "%",
    "slots": "",
    "set": " set.",
    "quest": "",
    "restrict": "",
    "lore": "",
}

BUILD_DETAILED_DISPLAY_COMMANDS: list[str] = [
    "#defense-stats-detailed",
    "!spacer",
    "mr", "ms", "#maxManaTotal",
    "hprRaw", "hprPct", "healPct",
    "ls",
    "!spacer",
    "sdRaw", "nSdRaw", "rSdRaw",
    "sdPct", "nSdPct", "rSdPct",
    "mdRaw", "nMdRaw", "rMdRaw",
    "mdPct", "nMdPct", "rMdPct",
    "damRaw", "nDamRaw", "rDamRaw",
    "damPct", "nDamPct", "rDamPct",
    "!elemental",
    "eSdRaw", "tSdRaw", "wSdRaw", "fSdRaw", "aSdRaw",
    "eSdPct", "tSdPct", "wSdPct", "fSdPct", "aSdPct",
    "eMdRaw", "tMdRaw", "wMdRaw", "fMdRaw", "aMdRaw",
    "eMdPct", "tMdPct", "wMdPct", "fMdPct", "aMdPct",
    "eDamRaw", "tDamRaw", "wDamRaw", "fDamRaw", "aDamRaw",
    "eDamPct", "tDamPct", "wDamPct", "fDamPct", "aDamPct",
    "eDefPct", "tDefPct", "wDefPct", "fDefPct", "aDefPct",
    "!elemental",
    "critDamPct",
    "!spacer",
    "rDefPct",
    "spPct1", "spRaw1", "spPct2", "spRaw2", "spPct3", "spRaw3", "spPct4", "spRaw4",
    "atkTier",
    "poison",
    "ref", "thorns",
    "expd",
    "spd",
    "sprint", "sprintReg",
    "jh",
    "xpb", "lb", "lq",
    "spRegen",
    "eSteal",
    "gXp", "gSpd",
    "kb", "weakenEnemy", "slowEnemy",
    "mainAttackRange",
]

SQ2_ITEM_DISPLAY_COMMANDS: list[str] = [
    "displayName",
    "atkSpd",
    "!elemental",
    "hp",
    "nDam_", "eDam_", "tDam_", "wDam_", "fDam_", "aDam_",
    "!spacer",
    "fDef", "wDef", "aDef", "tDef", "eDef",
    "!elemental",
    "classReq",
    "lvl",
    "strReq", "dexReq", "intReq", "defReq", "agiReq",
    "!spacer",
    "str", "dex", "int", "def", "agi",
    "hpBonus",
    "hprRaw", "hprPct", "healPct",
    "mr", "ms",
    "ref", "thorns",
    "ls",
    "poison",
    "expd",
    "spd",
    "atkTier",
    "sdRaw", "nSdRaw", "rSdRaw",
    "sdPct", "nSdPct", "rSdPct",
    "mdRaw", "nMdRaw", "rMdRaw",
    "mdPct", "nMdPct", "rMdPct",
    "damRaw", "nDamRaw", "rDamRaw",
    "damPct", "nDamPct", "rDamPct",
    "!elemental",
    "fSdRaw", "wSdRaw", "aSdRaw", "tSdRaw", "eSdRaw",
    "fSdPct", "wSdPct", "aSdPct", "tSdPct", "eSdPct",
    "fMdRaw", "wMdRaw", "aMdRaw", "tMdRaw", "eMdRaw",
    "fMdPct", "wMdPct", "aMdPct", "tMdPct", "eMdPct",
    "fDamRaw", "wDamRaw", "aDamRaw", "tDamRaw", "eDamRaw",
    "fDamPct", "wDamPct", "aDamPct", "tDamPct", "eDamPct",
    "fDefPct", "wDefPct", "aDefPct", "tDefPct", "eDefPct",
    "critDamPct",
    "!elemental",
    "rDefPct",
    "spPct1", "spRaw1", "spPct2", "spRaw2", "spPct3", "spRaw3", "spPct4", "spRaw4",
    "sprint", "sprintReg",
    "jh",
    "xpb", "lb", "lq",
    "spRegen",
    "eSteal",
    "gXp", "gSpd",
    "kb", "weakenEnemy", "slowEnemy", "maxMana",
    "mainAttackRange",
    "majorIds",
    "!spacer",
    "slots",
    "!spacer",
    "set",
    "lore",
    "quest",
    "restrict",
]


def format_stat(stat_id: str, value: Any) -> str | None:
    """Format a single stat for display.

    Returns None if the stat has no known label, the value is zero/empty,
    or the resulting string would be blank.
    """
    prefix = ID_PREFIXES.get(stat_id)
    if prefix is None:
        return None
    if value is None:
        return None
    if isinstance(value, (int, float)) and value == 0:
        return None
    if isinstance(value, str) and not value:
        return None
    suffix = ID_SUFFIXES.get(stat_id, "")
    line = f"{prefix}{value}{suffix}"
    return line if line else None


def format_stat_map(
    stat_map: dict[str, Any],
    display_order: list[str] | None = None,
) -> list[str]:
    """Format a stat map as ordered display lines.

    Directive entries starting with '!' or '#' are skipped.
    Stats absent from stat_map or with zero/empty values are omitted.
    """
    if display_order is None:
        display_order = SQ2_ITEM_DISPLAY_COMMANDS
    lines: list[str] = []
    for key in display_order:
        if key.startswith("!") or key.startswith("#"):
            continue
        value = stat_map.get(key)
        if value is None:
            continue
        line = format_stat(key, value)
        if line is not None:
            lines.append(line)
    return lines
